### PR TITLE
Age from stage vignette

### PR DESCRIPTION
**Pull request by patrickbarks**
Add age-from-stage vignette, simplify Install section of README, and rebuilt pkgdown site to reflect those updates.

### CODE REVIEW

**Comment by patrickbarks** [comment]
@jonesor DO NOT merge this before we talk, please!

May be better to leave until after the workshop.

**Comment by patrickbarks** [comment]
Travis-CI was down earlier and has a big queue, and I don't want to mess with the packagedown site at this stage, so I've temporarily posted the age-from-stage vignette at https://patrickbarks.github.io/age-from-stage/. Just for extra material in case we have some time to fill.

**Comment by jonesor** [comment]
@patrickbarks should I merge this and rebuild the pkgdown site now?

**Comment by patrickbarks** [comment]
@jonesor Yup, it's fine to merge. I've already re-run `pkgdown::build_site()`, so the site will be updated once this is merged if you just switch the GitHub Pages "Source" setting to "master branch /docs folder". This will mean that the site will be updated anytime we run `pkgdown::build_site()` and then push/merge to master, rather than being updated through Travis CI (which was leading to build errors).

**Pull request merged**
