### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by iainmstott**
New functionality for CompadreM and CompadreData classes.

I don't think I've touched any of the functions: I think all the work has been done on the CompadreM.R and particularly CompadreData.R files. I've added methods to access almost any part of the data I could think of. Some other functionality added, especially subsetting using square brackets [ ]. Check out the comments on the last commit and/or the comments in the code for a quick explanation. 

NOTE: 
1. I deleted the vignettes and test folder as they were screwing up my ability to check and build the package. Obviously these should be kept in.
2. I changed the name of the package (DESCRIPTION file) to RCompadreDev. This allowed me to install it alongside RCompadre. We may want to think about keeping this (with the caveat that when we merge devel into master, we'll need to change and change back).

The package passes devtools::check with no ERRORs, just warnings and notes. I haven't looked at these in detail because they don't really matter right now.

...I think that's it. If I've done anything else stupid just let me know.

### CODE REVIEW

**Comment by iainmstott** [comment]
@levisc8 honestly I'm not really sure what you mean with the NSE: are you able to give an example of how it would work?

Errors from tests and vignettes... I can't really remember what was going on. I changed all of the relevant functions (in tests at least), and I remember in tests there was one snippet that just wouldn't work (all the others did), and I couldn't work out why. I knew the vignettes were already throwing warnings before I created the fork. I just wanted to get on with it and make sure that the package would build, so I deleted the folders. I knew it would be possible to reincorporate them when it came to the pull request. Sorry I can't be more specific... (not much use I know)

Hopefully we can tweak everything easily to make it work. Help would be appreciated! If you can.

@tdjames1 Good first point. It would be easy enough to get the list index of that matrix object and then just call the existing function on the total database.

There are (now) accessors for mat and version. Actually there were (already) functions for this: I must have done something wrong with the previous commit. The new commit includes them (and some other stuff).

I think I may have used the i, j arguments of the standard `[` method wrong. But I'm not sure. It's something we should look into (slightly strange that it works on some systems and not others).

I *would* like the function to show a summary of the database, but couldn't decide how. The top of the database consists of one species, and even if you just show the first row, the output is big. If there's some way to summarise it well, without it taking up a load of room, then I'm very open to that. I think, though, that we might have to make it an optional argument.

I thought I'd got them all, but there must be either
1. an existing call to RCompadre somewhere in the code (e.g. examples)
2. RCompadre still exists in the NAMESPACE for some reason.
It wouldn't have shown up on my (and presumably Sam's) computer if we have a version of stable RCompadre already installed on our systems.

**Comment by tdjames1** [comment]
> It would be easy enough to get the list index of that matrix object and then just call the existing function on the total database.

I was thinking more of the `CompadreM` object having a metadata slot that contains the info.

> I would like the function to show a summary of the database, but couldn't decide how. The top of the database consists of one species, and even if you just show the first row, the output is big.

That's why I suggested a tibblesque approach: `tibble` shows only as many columns as fit but gives a summary of the remaining columns (useful if you can't remember what the column you want is called). Something similar to the output of `dplyr::glimpse()` might be another possible option. Whether or not to show the summary info could be controlled by an optional flag parameter to `show`.

I will check your updates and see if I can figure out the other things when I have a moment.

**Comment by patrickbarks** [comment]
Very cool!

This may not be directly related to this PR, but @tdjames1's comments made me wonder whether it could be possible to use a CompadreData object within a dplyr pipe sequence (%>%), e.g. to add a column to the metadata and then subset the whole db based on that new column -- all within a single 'line'.

In the past I've worked with a tibble version of the db (i.e. metatadata + list-columns for matA, matU ... , matrixClass) so that this type of thing is possible, e.g.

```
library(dplyr)

compadre_tb <- compadre$metadata %>% 
  as_tibble() %>% 
  mutate(matA = lapply(compadre$mat, function(x) x$matA),
         matU = lapply(compadre$mat, function(x) x$matU),
         matF = lapply(compadre$mat, function(x) x$matF),
         matC = lapply(compadre$mat, function(x) x$matC),
         matrixClass = compadre$matrixClass)

compadre_clean <- compadre_tb %>% 
  mutate(has_NA = sapply(matA, function(x) any(is.na(x)))) %>% 
  filter(has_NA == FALSE)
```

Could similar functionality be possible with a CompadreData object, with methods similar to the ones you've added here (or perhaps this is already possible)?

**Comment by iainmstott** [comment]
If there's a way we can do it that'll make it useful to the user, then we should. *But*, at this point I just want to warn against landing ourselves with too many dependencies (of course a few are fine). `dplyr` has something like a dozen imports I think, and if we're only going to use it to show an object, then I'm not sure I want to give ourselves the potential headache of having to accommodate future changes / deprecations to other people's code, or indeed packages being pulled from CRAN, although in the case that RStudio develops the packages I guess that's not massively likely.

**Comment by tdjames1** [comment]
I didn't say that we should actually use `dplyr` – I agree absolutely about not wanting it as a dependency due to its unwieldy nature – I was just saying that the ways it displays info might be worth considering :)

**Comment by iainmstott** [comment]
No but Patrick just suggested it ;)

**Comment by iainmstott** [comment]
Mind you, I'm not sure that we necessarily have to have the package as a an imports / dependency to use the generic methods. Never wondered about it before, perhaps it would just be Suggests. I'll look into it. But @patrickbarks perhaps you should create another issue with that suggestion as we're getting a little off-topic for this discussion

**Comment by jonesor** [comment]
Firstly, thanks for your patience! I've been overwhelmed with other things. 
Thanks @iainmstott  - I really like this. I'm not sure if/how what @iainmstott has done in his pull request affects the other restructuring Issues, but I'm just going to go ahead and merge this request. Can we add separate Issue(s) to address @levisc8's point about NSE support?

**Pull request merged**
